### ISSUE TITLE
Open on current window

### ISSUE THREAD

**Issue by danielbpb** [utomic-media/directus-extension-field-actions#43] opened 2023-08-31 03:27 UTC
Love your extension plugin, it works well. 

Just found a bug here. If we use this open link as a button on the list page, it will keep open a new tab/window regardless your link setting, is there any way we can change it behavior?

![Screenshot 2023-08-31 at 3 23 42 PM](https://github.com/utomic-media/directus-extension-field-actions/assets/122412385/3e7b1cfa-d698-4c64-82de-867f6ce21f46)
![Screenshot 2023-08-31 at 3 24 15 PM](https://github.com/utomic-media/directus-extension-field-actions/assets/122412385/bd2b6438-6f7a-44bc-b581-b7767f346df8)

**Comment by Dominic-Marcelino** [comment] 2023-08-31 07:57
Thanks for reporting the issue! I can confirm that the link-target setting currently doesn't work with the link-buttons. 

This issue is based on the default button-component of the drectus app that is used. It currently always sets the target to a new tab. I've opened an issue (https://github.com/directus/directus/issues/19560) + a pr (https://github.com/directus/directus/pull/19561) to the directus app that hopefully get's merged soon. 
Otherwise we'll build another solution for this extension.

 As a workaround might display the value (disable 'Hide field value') and select the 'Open link' link-action.

**Comment by danielbpb** [comment] 2023-08-31 21:37
Thank you for your quick response. Again, really love your work!

**Comment by Dominic-Marcelino** [comment] 2023-09-22 06:29
The issue is fixed with the release of [directus v10.6.2](https://github.com/directus/directus/releases/tag/v10.6.2)
There's no update needed on this extension.

**Closed by Dominic-Marcelino** 2023-09-22 06:29 UTC
